name: Build-Push-Deploy Prod

on:
  release:
    types: [released]

env:
  ENV: prod
  JIRA_URL: "https://kitabisa.atlassian.net"
  JIRA_USERNAME: "${{ secrets.JIRA_CLOUD_API_USER }}"
  JIRA_API_TOKEN: "${{ secrets.JIRA_CLOUD_API_TOKEN }}"
  WEBHOOK: "${{ secrets.BEUPS_JIRA_CREATE_RELEASE_WEBHOOK }}"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        shell: bash
        run:
          echo "Building"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        shell: bash
        run:
          echo "Deploying"
