name: Ollama GitHub Reviews

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
